export default {
    THEME_CHANGE:'THEME_CHANGE',
    THEME_INIT:'THEME_INIT',
    POPULAR_REFRESH:'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',  
    POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',  
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',  
    POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',  
    TRENGING_REFRESH:'TRENGING_REFRESH',
    TRENGING_REFRESH_FAIL:'TRENGING_REFRESH_FAIL',
    TRENGING_REFRESH_SUCCESS:'TRENGING_REFRESH_SUCCESS',
    TRENGING_LOAD_MORE_SUCCESS:'TRENGING_LOAD_MORE_SUCCESS',
    TRENGING_LOAD_MORE_FAIL:'TRENGING_LOAD_MORE_FAIL',
}